<a href="https://colab.research.google.com/github/dpcks/playdata/blob/main/06_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 란?
- 수치계산을 하기위한 파이썬 라이브러리
- 딥러닝에서 사용되는 텐서와 매우 유사
- 벡터와 행렬 단위의 대용량 수치 연산을 빠르게 진행
    - 병렬 연산한다.

- 벡터(vector)
    - 1차원 데이터(1차원 배열)
    - 스칼라가 연속적으로 여러개 모여 있는것
        - 스칼라(scalar): 단순하게 측정한 하나의 값
- 행렬 (Matrix)
    - 2차원 데이터(2차원 배열)
    - 1차원 데이터가 여러개 모여 있는 것



In [ ]:
import numpy as np

## 벡터

In [ ]:
lst = [1,2,3,4,5,6]
arr = np.array(lst)
arr 

array([1, 2, 3, 4, 5, 6])

## 행렬


In [ ]:
lst =[
    [1,2,3],
    [4,5,6]
]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

- 3차원 배열

In [ ]:
lst = [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
]

arr = np.array(lst)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
type(arr) # 타입 확인

numpy.ndarray

In [ ]:
arr.__len__()

2

In [ ]:
len(arr) # 첫번째 차원의 길이를 변환한다.

2

In [ ]:
arr.shape # 2행 2열 3차원

(2, 2, 3)

In [ ]:
arr = np.array([1,2,3,4,5])
arr.shape # 요소가 5개인 1차원

(5,)

## 인덱싱과 슬라이싱
- 기본적으로 파이썬에서 사용되는 인덱싱과 슬라이싱을 그대로 따라간다.


In [ ]:
arr[-1]

5

In [ ]:
print(arr[::-1])

[5 4 3 2 1]


## 자주쓰는 numpy 데이터 타입

In [ ]:
np.array([1,2,3],dtype = np.int32) # 4바이트 크기의 정수 1바이트가 8

array([1, 2, 3], dtype=int32)

In [ ]:
np.array([1,2,3],dtype=np.int64) # 8바이트 크기의 정수

array([1, 2, 3])

In [ ]:
np.array([1,2,3],dtype=np.uint8) # 1바이트 크기의 부호 없는 정수(0~255) ex) 이미지파일 ,u는 언사인이라는 의미 0부터 음수는 안댐

array([1, 2, 3], dtype=uint8)

In [ ]:
np.array([1,2,3],dtype=np.float32) # 4바이트 크기의 실수, 파이토치 딥러닝에서 기본값으로 사용

array([1., 2., 3.], dtype=float32)

In [ ]:
np.array([1,2,3],dtype=np.float64) # 4바이트 크기의 실수

array([1., 2., 3.])

In [ ]:
np.array([1,0,1],dtype=np.bool_)

array([ True, False,  True])

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr.shape[0] # 열개수   

4

In [ ]:
arr.shape[1] # 행 개수

3

- 다차원 슬라이싱

In [ ]:
arr[:,1]

array([ 2,  5,  8, 11])

In [ ]:
arr[:,::2]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [ ]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr[:,0]

array([ 1,  4,  7, 10])

In [ ]:
arr[:,:1] # 슬라이싱할때는 범위를 가져오므로 차원으로 가져온다

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [ ]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr[0::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
arr[:,1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [ ]:
arr[::2,::2]

array([[1, 3],
       [7, 9]])

## 마스킹(masking)
- bool 배열을 마스크로 사용하여 데이터의 특정 부분을 선택할 수 있다.


In [ ]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
mask_list = [True,False,True,False]
arr[mask_list]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
mask_list = [True,False,True]
arr[:,mask_list]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [ ]:
mask = arr > 2
mask

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr[mask] # 모든 스칼라에 마스킹을 할경우 벡터로 변환된다.

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

- 여러개의 인덱스 값들을 이용해서 가져오기

In [ ]:
index_list = [0,2]
arr[index_list] # 행

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
index_list = [0,2]
arr[:,index_list] # 열

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

# numpy 함수 알아보기

## 배열의 각 요소별로 연산

In [ ]:
arr1 = np.array([1,5,1])
arr2 = np.array([3,2,7])

np.add(arr1,arr2) # arr1 + arr2  # 병렬연산 가능

array([4, 7, 8])

In [ ]:
np.subtract(arr1,arr2) # arr1 - arr2 

array([-2,  3, -6])

In [ ]:
np.multiply(arr1,arr2) #arr * arr2

array([ 3, 10,  7])

In [ ]:
np.divide(arr1,arr2) # arr1 / arr2

array([0.33333333, 2.5       , 0.14285714])

In [ ]:
np.abs(arr1 - arr2)  # 절대값

array([2, 3, 6])

- 브로드캐스팅(Broadcasting)
    - 배열의 모양이 다르더라도 어떠한 조건이 만족했을때 작은 배열을 자동으로 큰배열 크기에 맞춘다.
    

In [ ]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
arr 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr * 2 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [ ]:
[2,2,2],
[2,2,2],
[2,2,2],
[2,2,2]

In [ ]:
arr * np.array([1,2,3]) # 열의 크기를 맞춰주면 행이 늘어난다.

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27],
       [10, 22, 36]])

In [ ]:
arr * np.array([ # 행의 크기를 맞춰주면 열이 늘어난다.
    [1],
    [2],
    [3],
    [4]
])

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27],
       [40, 44, 48]])

- Norm
    - 벡터의 크기를 측정하는 함수

In [ ]:
np.linalg.norm([-1,2,3],1) # L1 norm

6.0

In [ ]:
np.linalg.norm([-1,2,3]) # L2 norm

3.7416573867739413

- 내적(dot product)
    - 두 벡터의 각 요소끼리 곱의 합
    - 결과값은 스칼라가 나온다

In [ ]:
a = np.array([3,2,2]) # 사과, 딸기 ,참외 빈도수
b = np.array([2,1,2]) 
np.dot(a,b)

12

In [ ]:
a @ b

12

- 행렬곱
    - 2차원 공간에서 내적을 한다.
    - 앞에 행렬의 열개수와 뒤에 행렬의 행개수가 동일해야한다.
    - 연산결과의 shape는 앞에 행렬의 행개수와 뒤에 행렬의 열개수가 나온다.


In [ ]:
x = np.array([
    # 한행은 한학생의 과거 모의고사 점수
    [80,90,70],
    [81,93,72],
    [71,73,62],
    [61,10,12] 
]) 

In [ ]:
w = np.array([ # 가중치를 구하고 내적한후 실제점수와 오차값을 구한다. 다중회귀로 활용할 수 있다.
    [0.4],
    [0.2],
    [0.3]
])
x @ w

array([[71. ],
       [72.6],
       [61.6],
       [30. ]])

In [ ]:
y = np.array([
    # 실제 시험에서의 점수
    [77],
    [80],
    [71],
    [65]
])

# 배열 만들기

- `np.arange`
    - `range` 함수와 비슷하지만 ndarray 가 반환된다.

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,6,2)

array([3, 5])

- `np.zeros`
    - 0 으로 채워진 배열 만들기

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

- `np.ones`
    - 1로 채워진 배열 만들기

In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- `np.full`
    - 지정한 값으로 채워진 배열을 만들때..

In [ ]:
np.full([3,5],True)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
np.full([3,5],100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

# numpy 집계함수

In [ ]:
scores = np.array([80,90,100,70,40,90])

In [ ]:
np.sum(scores) , scores.sum()

(470, 470)

In [ ]:
np.mean(scores), scores.mean()

(78.33333333333333, 78.33333333333333)

In [ ]:
np.median(scores) # 중앙값 함수만 있음

85.0

In [ ]:
np.std(scores) # 표준편차

19.50783318453271

In [ ]:
np.var(scores) # 분산

380.5555555555556

In [ ]:
np.max(scores) , scores.max() # 최댓값

(100, 100)

In [ ]:
np.min(scores), scores.min() # 최솟값 

(40, 40)

In [ ]:
np.argmin(scores) # 데이터의 최솟값 인덱스 반환

4

In [ ]:
np.argmax(scores) # 데이터의 최대값 인덱스 반환

2

In [ ]:
arr = np.array([1,3,3,3,6,6,6,6,6])
np.unique(arr) # 고유값만 보기(중복제거)

array([1, 3, 6])

In [ ]:
np.square([2,3,4]) # 각 요소에 제곱

array([ 4,  9, 16])

In [ ]:
np.sqrt([2,3,4]) # 각 요소에 루트

array([1.41421356, 1.73205081, 2.        ])

In [ ]:
np.round([5.3,7.5,8.8],1) # 반올림 , 소수점 첫째짜리까지만 반올림하겠다

array([5.3, 7.5, 8.8])

In [ ]:
np.ceil([5.2,4.8,5.9]) # 올림

array([6., 5., 6.])

In [ ]:
np.floor([5.2,4.8,5.9]) #버림

array([5., 4., 5.])

- exp 함수 : $y=e^x$
    - 자연상수인 오일러의 수를 밑으로하는 지수함수
    - x 에 0이 들어가면 1, 1이 들어가면 오일러의 수가 나온다.
    - x 값이 조금만 커져도 무한대로 빠진다.

In [ ]:
np.exp(1000)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


inf

In [ ]:
np.exp(0)

1.0

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.exp([1,2,3])

array([ 2.71828183,  7.3890561 , 20.08553692])

## 자연로그 함수: $y=\log_e x$
- 오일러수를 밑으로하는 로그함수
- x에 0이하가 들어가면 무한대, 1이 들어가면 0



In [ ]:
np.log([0,1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf,   0.])

In [ ]:
np.log(12312323123123123)

37.049377035671036

- 분위수
    - 데이터를 크기 순서에 따른 위치값
    - 이상치 영향을 덜 받는다.
    - 0.5를 줄 경우 중앙값이 나온다

In [ ]:
arr = np.array([100,3,3,6,7,9,20,10,9])
np.quantile(arr,0.5) , np.median(arr) , np.mean(arr)

(9.0, 9.0, 18.555555555555557)

In [ ]:
np.max(arr) * 0.9

90.0

In [ ]:
np.quantile(arr,0.9)

36.000000000000014

In [ ]:
np.quantile(arr,[0,0.25,0.5,0.75,1]) # 4등분한 경우

array([  3.,   6.,   9.,  10., 100.])

- 정렬


In [ ]:
np.sort(arr)

array([  3,   3,   6,   7,   9,   9,  10,  20, 100])

In [ ]:
np.sort(arr)[::-1] # 내림차순

array([100,  20,  10,   9,   9,   7,   6,   3,   3])

## 배열 조건연산

In [ ]:
scores = np.array([80,90,100,70,40,90])
scores

array([ 80,  90, 100,  70,  40,  90])

In [ ]:
scores >= 80

array([ True,  True,  True, False, False,  True])

- `np.any`
     - 조건에 참이 하나라도 있으면 True

In [ ]:
np.any(scores >= 100)

True

- `np.all`
    - 조건이 모두 참이면 True

In [ ]:
np.all(scores >= 70) # 2개의 배열 요소가 같은지 확인할때 사용

False

In [ ]:
np.all(scores == scores) # 2개의 배열 요소가 같은지 확인할때 사용

True

- `np.where`
    

In [ ]:
np.where(scores >= 80 , 1, 0)

array([1, 1, 1, 0, 0, 1])

In [ ]:
np.where(scores >= 80 , scores,0)

array([ 80,  90, 100,   0,   0,  90])

In [ ]:
arr = np.array([
    [1,2,3],
    [0,0,3],
    [0,5,3]
])
arr

array([[1, 2, 3],
       [0, 0, 3],
       [0, 5, 3]])

In [ ]:
np.where(arr > 0, 1,arr)

array([[1, 1, 1],
       [0, 0, 1],
       [0, 1, 1]])

- `np.clip`
    - (array,min,max)
    - 배열에 요소에 min 보다 작으면 min으로 변경
    - max 보다 크면 max값으로 변경

In [ ]:
arr

array([[1, 2, 3],
       [0, 0, 3],
       [0, 5, 3]])

In [ ]:
np.clip(arr, 1,3)

array([[1, 2, 3],
       [1, 1, 3],
       [1, 3, 3]])

In [ ]:
np.clip(arr,[1,3,1],[3,4,2]) #하나의 열이라고 생각하면됨

array([[1, 3, 2],
       [1, 3, 2],
       [1, 4, 2]])

- 무한대값

In [ ]:
np.inf

inf

nan 값(결측치)


In [ ]:
np.nan

nan

- 전처리 과정에서 nan, inf값이 생겼다고 가정

In [ ]:
arr = np.array([np.inf,np.nan, 4,5,7,8.1])
arr

array([inf, nan, 4. , 5. , 7. , 8.1])

- 무한대값 찾기

In [ ]:
np.isinf(arr)

array([ True, False, False, False, False, False])

In [ ]:
# arr[np.isinf(arr)]=0
# arr

- nan 값 찾기

In [ ]:
np.isnan(arr)

array([False,  True, False, False, False, False])

- 셀수 있는 정상 수치 찾기

In [ ]:
np.isfinite(arr)

array([False, False,  True,  True,  True,  True])

In [ ]:
arr[np.isfinite(arr) == False] = 0 # 무한대 값과 nan 값 0으로 초기화하기
arr

array([0. , 0. , 4. , 5. , 7. , 8.1])

In [ ]:
arr = np.array([4,5,np.inf,7,8.1,np.nan])
arr

array([4. , 5. , inf, 7. , 8.1, nan])

In [ ]:
np.isnan(arr)

array([False, False, False, False, False,  True])

In [ ]:
np.isinf(arr)

array([False, False,  True, False, False, False])

In [ ]:
np.isfinite(arr)

array([ True,  True, False,  True,  True, False])

In [ ]:
arr[np.isfinite(arr)== False] = 100
arr

array([  4. ,   5. , 100. ,   7. ,   8.1, 100. ])

In [ ]:
arr = np.array([
    [1,2,3],
    [np.inf,0,3],
    [0,5,np.nan]
])
arr

array([[ 1.,  2.,  3.],
       [inf,  0.,  3.],
       [ 0.,  5., nan]])

In [ ]:
np.isnan(arr)

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [ ]:
arr[np.isfinite(arr)== False ]= 0
arr

array([[1., 2., 3.],
       [0., 0., 3.],
       [0., 5., 0.]])

# numpy random

- rand 함수
    - 0~1 사이에 랜덤값 반환

In [ ]:
np.random.seed(42)
np.random.rand()

0.3745401188473625

In [ ]:
np.random.rand(3,3,4)

array([[[0.15601864, 0.15599452, 0.05808361, 0.86617615],
        [0.60111501, 0.70807258, 0.02058449, 0.96990985],
        [0.83244264, 0.21233911, 0.18182497, 0.18340451]],

       [[0.30424224, 0.52475643, 0.43194502, 0.29122914],
        [0.61185289, 0.13949386, 0.29214465, 0.36636184],
        [0.45606998, 0.78517596, 0.19967378, 0.51423444]],

       [[0.59241457, 0.04645041, 0.60754485, 0.17052412],
        [0.06505159, 0.94888554, 0.96563203, 0.80839735],
        [0.30461377, 0.09767211, 0.68423303, 0.44015249]]])

- `randn`
    - 평균이 0이고 분산이 1인 정규분포 형태의 랜덤값들을 반환

In [ ]:
np.random.seed(42)
arr = np.random.randn(100000)
arr

array([ 0.49671415, -0.1382643 ,  0.64768854, ...,  0.40918508,
       -0.21109167,  0.12006294])

In [ ]:
arr.var(), arr.mean()

(1.0018027203084223, 0.000966868140949598)

- randint
    - 랜덤한 정수 반환
    - start ~ end-1
    - 세번째 인자는 크기
    

In [ ]:
np.random.seed(42)
arr = np.random.randint(50,100)
arr

88

In [ ]:
np.random.randint(50,100,(4,3))

array([[78, 64, 92],
       [57, 70, 88],
       [68, 72, 60],
       [60, 73, 85]])

- `shuffle`
    - 반환값이 없고 배열 자체를 섞는다.

In [ ]:
np.random.seed(42)
arr = np.arange(1,7)
np.random.shuffle(arr)
arr

array([1, 2, 6, 3, 5, 4])

- `choice`
    - 지정한 개수 만큼 랜덤하게 선택해서 추출

In [ ]:
np.random.choice(5,3) # 0~4 사이에 3개의 값을 랜덤하게 추출하겠다.

array([3, 3, 2])

In [ ]:
np.random.choice(5,3,replace=False) # 중복값이 안나오게 하기

array([1, 0, 3])

In [ ]:
np.random.choice(5,3,p=[1,0,0,0,0]) # 확률주기

array([0, 0, 0])

In [ ]:
np.random.choice(5,3,p=[0.5,0.2,0.1,0.1,0.1]) # 확률도 줄수있다. p 인수의 합은 1 !

array([0, 4, 2])

In [ ]:
arr = np.array([10,20,30,40,50,60,70])
np.random.choice(arr,3,replace = False)

array([60, 30, 40])

In [ ]:
arr= np.random.randint(50,100,(5,3))
idx_list = np.random.choice(len(arr),3, replace=False)
arr[idx_list]

array([[81, 88, 98],
       [94, 64, 92],
       [81, 53, 79]])

# axis 이해하기

In [ ]:
np.random.seed(42)
arr = np.random.randint(50,91,[4,3])
arr

array([[88, 78, 64],
       [57, 70, 88],
       [68, 72, 60],
       [60, 73, 85]])

In [ ]:
arr.sum(axis=0) # 각 열에 대한 총합

array([273, 293, 297])

In [ ]:
arr.sum(axis=1)

array([230, 215, 200, 218])

- 3차원 

In [ ]:
np.random.seed(42)
arr = np.random.randint(50,91,[4,3,2])
arr

array([[[88, 78],
        [64, 57],
        [70, 88]],

       [[68, 72],
        [60, 60],
        [73, 85]],

       [[89, 73],
        [52, 71],
        [51, 73]],

       [[79, 87],
        [51, 70],
        [82, 61]]])

In [ ]:
arr.sum(axis=1)

array([[222, 223],
       [201, 217],
       [192, 217],
       [212, 218]])

In [ ]:
arr.mean(axis=1)

array([[74.        , 74.33333333],
       [67.        , 72.33333333],
       [64.        , 72.33333333],
       [70.66666667, 72.66666667]])

In [ ]:
arr.sum(axis =2)

array([[166, 121, 158],
       [140, 120, 158],
       [162, 123, 124],
       [166, 121, 143]])

In [ ]:
arr.mean(axis=2)

array([[83. , 60.5, 79. ],
       [70. , 60. , 79. ],
       [81. , 61.5, 62. ],
       [83. , 60.5, 71.5]])

In [ ]:
np.random.seed(42)
arr = np.random.randint(50,91,[4,3,2])
arr

array([[[88, 78],
        [64, 57],
        [70, 88]],

       [[68, 72],
        [60, 60],
        [73, 85]],

       [[89, 73],
        [52, 71],
        [51, 73]],

       [[79, 87],
        [51, 70],
        [82, 61]]])

In [ ]:
arr.sum(axis=2)[1::]

array([[140, 120, 158],
       [162, 123, 124],
       [166, 121, 143]])

# 배열 차원 변경 및 새로운 차원 추가

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[:,np.newaxis] # 6행 1열  2차원 열벡터

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
np.expand_dims(arr,axis = 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

- reshape는 요소의 순번대로 차원을 변경한다.

In [ ]:
arr.reshape(-1,1) # -1 요소들을 다쓰고 차원들을 추가 하겠다.

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
arr.reshape(2,3) # 2행 3열로 바꾸겠다

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2 = np.reshape(arr,[2,3])
arr2

array([[0, 1, 2],
       [3, 4, 5]])

- 전치
    - `reshape`와 transpose는 다르다
    - `transpose`는 차원을 맞바꾼다.
    - `reshape`는 원소의 순서대로 재배치하면서 차원을 변경

In [ ]:
np.transpose(arr2) # 행이 열이되고 열이 행이됨

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr2.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr = np.arange(12)
arr= arr.reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
arr.transpose(0,2,1)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

- 평평하게 만들기

In [ ]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 차원이 1인 차원 제거

In [ ]:
np.random.seed(42)
arr = np.random.randint(50,91,[4,1,2,1])
arr.shape

(4, 1, 2, 1)

In [ ]:
arr.squeeze()

array([[88, 78],
       [64, 57],
       [70, 88],
       [68, 72]])

In [ ]:
arr.squeeze(axis=1).shape # 흑백이미지 칼라는 뒤에가 3

(4, 2, 1)

# 배열 합치기

- `concatenate`함수 
    - axis 방향으로 배열을 합친다.

In [ ]:
arr1 = np.array([
    [1,2],
    [3,4],
    [5,6]
])

arr2 = ([

    [10,20]
])

In [ ]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20]])

In [ ]:
arr2 = np.array([
    [10],
    [20],
    [30]
])
np.concatenate([arr1,arr2],axis =1 ) # 열방향으로 합치기

array([[ 1,  2, 10],
       [ 3,  4, 20],
       [ 5,  6, 30]])

- stack 함수
    - 합치려는 차원크기가 모두 동일해야한다.
    - 합치려는 배열이 하나의 행으로 취급된다.
    

In [ ]:
arr1 = np.array([
    [1,2],
    [3,4],
    [5,6]
])

arr2 = ([

    [10,20]
])
np.stack([arr1,arr2],axis=0) # 차원에 크기가 모두 동일하지 않아 에러발생 ! 행의 크기가 같지않음

ValueError: ignored

In [ ]:
arr2 = np.array([
    [10,20],
    [30,40],
    [50,60]
])
np.stack([arr1,arr2]).shape

(2, 3, 2)

- numpy 배열 리스트로 변경하기

In [ ]:
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
list(arr)

[array([0, 1, 2]), array([3, 4, 5])]

In [ ]:
arr.tolist()

[[0, 1, 2], [3, 4, 5]]

In [ ]:
arr.copy()

array([[0, 1, 2],
       [3, 4, 5]])

# numpy 배열 파일로 저장하기

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.save("arr",arr) # 확장자 생략시 .npy가 붙는다.

In [ ]:
np.load("arr.npy")

array([[0, 1, 2],
       [3, 4, 5]])

- 배열 복사하기(기본적으로 깊은 복사)

In [ ]:
arr2 = arr.copy()

In [ ]:
np.random.seed(42)
arr = np.random.randint(1,5,[4,3,2])
arr

array([[[3, 4],
        [1, 3],
        [3, 4]],

       [[1, 1],
        [3, 2],
        [3, 3]],

       [[3, 3],
        [4, 1],
        [4, 4]],

       [[4, 3],
        [2, 1],
        [2, 4]]])

array([], shape=(0, 2), dtype=int64)

In [ ]:
np.random.seed(42)
arr = np.random.randint(1,5,[3,2])
arr

array([[3, 4],
       [1, 3],
       [3, 4]])

In [ ]:
np.sum(arr,axis =0)

array([ 7, 11])